### PR TITLE
Upmerge to zcbor 0.7.0

### PR DESCRIPTION
**Pull request by oyvindronningstad**
https://github.com/zephyrproject-rtos/zephyr/pull/56471

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
Ping @carlescufi @de-nordic

**Comment by de-nordic** [comment]
Is there Zephyr west.yaml manifest update testing this change?

**Comment by oyvindronningstad** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/56471

**Comment by de-nordic** [comment]
This seem to cause some  problems with lwm2m in Zephyr. Fix needed in Zephyr PR before this can be accepted.

**Comment by oyvindronningstad** [comment]
@de-nordic Green now.

**Comment by oyvindronningstad** [comment]
And now approved

https://github.com/zephyrproject-rtos/zephyr/pull/56471

**Review by de-nordic — APPROVED** [review]

**Pull request merged**
